name: Build and Push Kind Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      kubernetes_version:
        description: 'Kubernetes Version'
        required: true
        default: 'v1.23.10'
        type: string
      minikube_version:
        description: 'Minikube Version'
        required: true
        default: 'v1.27.1'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: 
          - v1.23.10
        include:
          - kubernetes_version: v1.23.10
            minikube_version: v1.27.1
            docker_image: 20.10.20-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        # Only login when pushing to main/master branch, not on pull requests
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Kind Image
        run: |
          chmod +x ./build.sh
          ./build.sh nosugarcoffee/kind:latest-${{ matrix.kubernetes_version }} nosugarcoffee/kind:${{ github.sha }}-${{ matrix.kubernetes_version }}
        env:
          KUBERNETES_VERSION: ${{ matrix.kubernetes_version }}
          MINIKUBE_VERSION: ${{ matrix.minikube_version }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}

      - name: Push Docker image
        # Only push when on main/master branch, not on pull requests
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          docker push nosugarcoffee/kind:latest-${{ matrix.kubernetes_version }}
          docker push nosugarcoffee/kind:${{ github.sha }}-${{ matrix.kubernetes_version }}
