name: Build and Push Kind Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      kubernetes_version:
        description: 'Kubernetes Version'
        required: true
        default: 'v1.23.10'
        type: string
      minikube_version:
        description: 'Minikube Version'
        required: true
        default: 'v1.27.1'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version: 
          - v1.23.10
        include:
          - kubernetes_version: v1.23.10
            minikube_version: v1.27.1
            docker_image: 20.10.20-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tags
        id: generate-tags
        run: |
          # For main/master branch pushes or manual workflow runs
          if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "BUILD_TAG=liangliangdai/kind:latest-${{ matrix.kubernetes_version }}" >> $GITHUB_OUTPUT
            echo "VERSION_TAG=liangliangdai/kind:${{ matrix.kubernetes_version }}" >> $GITHUB_OUTPUT
          # For pull requests
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "BUILD_TAG=liangliangdai/kind:${SHORT_SHA}-${{ matrix.kubernetes_version }}" >> $GITHUB_OUTPUT
            echo "VERSION_TAG=liangliangdai/kind:${SHORT_SHA}-${{ matrix.kubernetes_version }}" >> $GITHUB_OUTPUT
          fi

      - name: Build Kind Image
        run: |
          chmod +x ./build.sh
          ./build.sh ${{ steps.generate-tags.outputs.BUILD_TAG }} ${{ steps.generate-tags.outputs.VERSION_TAG }}
        env:
          KUBERNETES_VERSION: ${{ matrix.kubernetes_version }}
          MINIKUBE_VERSION: ${{ matrix.minikube_version }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}

      - name: Push Docker image for PR
        if: github.event_name == 'pull_request'
        run: |
          echo "Pushing PR image: ${{ steps.generate-tags.outputs.VERSION_TAG }}"
          docker push ${{ steps.generate-tags.outputs.VERSION_TAG }}

      - name: Push Docker images for main/master
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          echo "Pushing latest and versioned images"
          docker push ${{ steps.generate-tags.outputs.BUILD_TAG }}
          docker push ${{ steps.generate-tags.outputs.VERSION_TAG }}